apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbtest
spec:
  selector:
    matchLabels:
      app: mongodbtest
  template:
    metadata:
      labels:
        app: mongodbtest
    spec:
      containers:
      - name: nodeserver
        image: narashi/mongodbtest:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

  
