apiVersion: v1
kind: Service
metadata:
  name: mongodbtest-service
spec:
  selector:
    app: mongodbtest
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110
